const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
const morgan = require('morgan')
const cookieParser = require('cookie-parser')
require('dotenv').config()
const authRoutes = require('./src/routes/authRoutes')
const productRoutes = require('./src/routes/productRoutes')
const categoryRoutes = require('./src/routes/categoryRoutes')
const cartRoutes = require('./src/routes/cartRoutes')
const wishlistRoutes = require('./src/routes/wishlistRoutes')
const orderRoutes = require('./src/routes/orderRoutes')
const reviewRoutes = require('./src/routes/reviewRoutes')
const uploadRoutes = require('./src/routes/uploadRoutes')
const userRoutes = require('./src/routes/userRoutes')
const couponRoutes = require('./src/routes/couponRoutes')
const settingsRoutes = require('./src/routes/settingsRoutes')
const app = express()

app.use(helmet())
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true }))
app.use(express.json())
app.use(cookieParser())
app.use(morgan('dev'))
app.use('/api/auth', authRoutes)
app.use('/api/products', productRoutes)
app.use('/api/categories', categoryRoutes)
app.use('/api/cart', cartRoutes)
app.use('/api/wishlist', wishlistRoutes)
app.use('/api/orders', orderRoutes)
app.use('/api/reviews', reviewRoutes)
app.use('/api/upload', uploadRoutes)
app.use('/api/users', userRoutes)
app.use('/api/coupons', couponRoutes)
app.use('/api/settings', settingsRoutes)

app.get('/', (req, res) =>{
    res.json({ message: 'Server is running' })
})

module.exports = app